[package]
name = "reflect-struct-macro-derive"
version = "0.1.0"
authors = ["dgr113 <dmitry-gr87@yandex.ru>"]
edition = "2018"


[lib]
proc-macro = true


[dependencies]
quote = "^1.0"
syn = { version = "^1.0", features = ["full"] }
